### ISSUE TITLE
Make hero text contrast 508 compliant

### ISSUE THREAD

**Issue by mollieru** [us-federal-sbst/federalist-modern-team-template#1]
I have been previously informed that text on images frequently fails 508 standards.  Double check that this is ok w the opacity of the block you've got behind the text. 

![screen shot 2015-09-08 at 5 31 48 pm](https://cloud.githubusercontent.com/assets/3680494/9748011/9070581a-564f-11e5-93a6-56e7f4d5fcaf.png)

**Comment by GailSwanson** [comment]
Use #344058 at 50% opacity for the block. This, plus moving the block lower should solve any issues.

**Comment by GailSwanson** [comment]
The block has to be moved to the lower half of the image (on the darer area), or we have to increase the opacity of the background in order to be in compliance with 508 standards.

**Comment by dhcole** [comment]
Done
