### ISSUE TITLE
Limit text width on inner pages

### ISSUE THREAD

**Issue by maya** [us-federal-sbst/federalist-modern-team-template#10]
The text feels too long per line here: https://federalist.18f.gov/preview/us-federal-sbst/federalist-modern-team-template/staging/approach/

Either add it into a two thirds grid class or add the `usa-content` class to the text container to give it a max-width.

Reference: https://pages-staging.18f.gov/usfwds/visual-style/#typesetting

**Comment by jeremiak** [comment]
Hmm interesting idea. Have you found that people think it looks weird/broken if the text doesn't go all the way to the edge? http://up.jeremiak.com/d4ac
