### ISSUE TITLE
Center header links on mobile

### ISSUE THREAD

**Issue by maya** [us-federal-sbst/federalist-modern-team-template#11]
I'd center the nav links as the base style (mobile first), and then add a style for larger screens so that it floats right.

<img width="384" alt="screen shot 2015-09-08 at 7 12 44 pm" src="https://cloud.githubusercontent.com/assets/5249443/9751767/a67496ea-565d-11e5-89cd-5b4f21b06f9c.png">

**Comment by maya** [comment]
Might want to center the logo too.

**Comment by jeremiak** [comment]
@maya I think I want to do a similar thing that you do with the sidenav which is to make each link take up the full width of the viewport and center it. What do you think?

**Comment by maya** [comment]
@jeremiak I think I'd have to see what u mean to get a better idea. The sidebar pattern is really good for a lot of links, but if you just have three links it should be fine to have them on a single line.

**Comment by GailSwanson** [comment]
What are your thoughts about a hamburger menu so that you can see some content on mobile w/o scrolling?

**Comment by jeremiak** [comment]
@GailSwanson I would like to see a hamburger menu, but wanted to just get something out the door that worked.

@maya are there plans for the pattern lib to handle this for us?

**Comment by jeremiak** [comment]
Closing this issue since I have centered the logo and the menu items. We can open a new issue if we want to change the functionality to a hamburger menu
