### ISSUE TITLE
Add 2015 Annual Report to Work subnav

### ISSUE THREAD

**Issue by GailSwanson** [us-federal-sbst/federalist-modern-team-template#20]
Sub nav for Work section should contain the 2015 Annual Report and each Case Study.
![screen shot 2015-09-10 at 11 20 46 am](https://cloud.githubusercontent.com/assets/12940398/9793978/13f2c646-57ae-11e5-9e93-b8b55aa3e58a.png)

**Comment by GailSwanson** [comment]
Looks like it's been added. I thought there was supposed to be a separate page, not that this would go to the Work landing page.

**Comment by jeremiak** [comment]
@GailSwanson The destination of the link is easily configured in `_data/projects.yml`. If we want it to go to another page, we can. I was thinking we would change out that link to link to the PDF once we get it next week.

**Comment by jeremiak** [comment]
Looks like it even goes to [another page](http://federalist.18f.gov.s3-website-us-east-1.amazonaws.com/site/us-federal-sbst/federalist-modern-team-template/2015-annual-report/) right now. I think we can close this issue
