### ISSUE TITLE
Update color palette to use Web Design Standards

### ISSUE THREAD

**Issue by mollieru** [us-federal-sbst/federalist-modern-team-template#3]
Recommend the following subtle replacements, using hex codes from the Web Design Standards:

teal > #046b99
coral > #e31c3d

**Comment by maya** [comment]
The colors that @mollieru is recomending maps to our variables $color-primary-alt-darkest and $color-secondary.

**Comment by maya** [comment]
@jeremiak @dhcole I played around with some colors here:

![ub89yqwjegeaaaaasuvork5cyii](https://cloud.githubusercontent.com/assets/5249443/9751657/330ac2a2-565c-11e5-8451-87d7d1a45a96.png)

**Comment by maya** [comment]
Might want to update your base text from teal to our base text color, too.

**Comment by GailSwanson** [comment]
The client has their own color pallet that we need to use as closely as possible. It's a departure from the standards, but that is expected.

Their color pallet is:
![image](https://cloud.githubusercontent.com/assets/12940398/9776230/eb3deb14-571b-11e5-97c1-44f6ef0dc53e.png)

Yellow: #F3C536
Orange: #FB8341
Red: #FD553F
Blue: #2599C6
Teal: #00CBB9

**Comment by GailSwanson** [comment]
How do people feel about this? I had to massage the blue and red a bit to get it 508 compliant.
![color preview1](https://cloud.githubusercontent.com/assets/12940398/9776844/82edd3ec-5722-11e5-908e-25653566cc30.png)

**Comment by GailSwanson** [comment]
*Text Colors*
Headings and body copy--
#227292 text white background
or
White text on #227292 background

Button
Background #C11802 with white text
Background hover: #981b1e with white text

**Comment by dhcole** [comment]
All done
