### ISSUE TITLE
Center US site notice

### ISSUE THREAD

**Issue by dhcole** [us-federal-sbst/federalist-modern-team-template#6]
The notice on the top seems better centered:

<img width="391" alt="screen shot 2015-09-08 at 5 47 28 pm" src="https://cloud.githubusercontent.com/assets/170641/9748285/c39b3992-5651-11e5-9afe-86730502db81.png">

**Comment by maya** [comment]
That's a good call, the original design was for having stage text on the right and the official notice on the left. But if you will only have one notice, that's is a good way to go.

<img width="1229" alt="screen shot 2015-09-08 at 6 45 36 pm" src="https://cloud.githubusercontent.com/assets/5249443/9751448/e53c8616-5659-11e5-9e1b-35c4d143f74e.png">
