### ISSUE TITLE
Consider less wide hero text

### ISSUE THREAD

**Issue by dhcole** [us-federal-sbst/federalist-modern-team-template#7]
Seems like the hero text could be less wide to cover less of the background image, and the text could wrap an additional line:

<img width="1075" alt="screen shot 2015-09-08 at 4 58 42 pm" src="https://cloud.githubusercontent.com/assets/170641/9747310/fa89f1e8-564a-11e5-892f-1d02963b4316.png">

<img width="1266" alt="screen shot 2015-09-08 at 5 02 01 pm" src="https://cloud.githubusercontent.com/assets/170641/9747404/5a59dd04-564b-11e5-8939-ff6777bde3f5.png">

**Comment by GailSwanson** [comment]
We need to move the block closer to the bottom of the photo. We can't have it cover POTUS face like that and it would be great not to cover the team's faces. It balances nicely if we move it to the bottom with a 20px bottom margin. 

We can cut the padding (within the box) to 20 px as well. That shrinks the box considerably.

**Comment by GailSwanson** [comment]
![screen shot 2015-09-09 at 5 50 59 pm](https://cloud.githubusercontent.com/assets/12940398/9776186/6099d59a-571b-11e5-8e9c-b21d6e84017c.png)

**Comment by GailSwanson** [comment]
Should end up looking like this:
![screen shot 2015-09-09 at 8 49 55 pm](https://cloud.githubusercontent.com/assets/12940398/9778320/5a8413e6-5734-11e5-8171-caafab10c365.png)
