### ISSUE TITLE
Update fonts

### ISSUE THREAD

**Issue by maya** [us-federal-sbst/federalist-modern-team-template#8]
I think updating the fonts to use something in our family would give it some more polish and finish. What do you think @angel and @mollieru

Here's what it looks like in Source Sans Pro:

![mkefu225jooaaaaasuvork5cyii](https://cloud.githubusercontent.com/assets/5249443/9751498/85f16496-565a-11e5-8f89-a521bb822c43.png)

**Comment by GailSwanson** [comment]
Montserrat or Lato are the closest web fonts to what was in the comps.

**Comment by GailSwanson** [comment]
Same sizes, just changed the typeface to Lato

H1:  Lato-regular 40px, 50px line height 
H2:  Lato-regular 36px, 50px line height 
H3:  Lato-regular 30px, 40px line height  
Body:  Lato-regular 18px, 30 line height #000000

Button height 44px
Button text:  Lato-regular 22px

**Comment by GailSwanson** [comment]
Text block max width = 625 px. If subnav is not on page, center copy blocks, with text aligned left. 
![screen shot 2015-09-09 at 7 35 39 pm](https://cloud.githubusercontent.com/assets/12940398/9777432/0c747ad8-572a-11e5-9a71-2ac9bf85490f.png)

**Comment by maya** [comment]
Lato is a great font

**Comment by mollieru** [comment]
Would love to see this use the web design standards fonts if there isn't a
typeface connected to the client's brand. Lots of work went into vetting
and testing different fonts (including Lato) -- would be awesome to see how
these fit into a relatively brand agnostic site on Federalist as an early
example.

Obviously biased in that preference :)

**Comment by GailSwanson** [comment]
We originally sent them comps using the design standards fonts, and they decided to go with something different because the wanted to look different than a 'government site'. It did look awesome in the original though. I can send you the version once I dig it out.

**Comment by GailSwanson** [comment]
Clicked the wrong button.

**Comment by dhcole** [comment]
Should be all set.
